### ISSUE TITLE
cant Use layout simple

### ISSUE THREAD

**Issue by socktow** [RCVolus/lol-pick-ban-ui#16] opened 2020-06-12 11:40 UTC
![image](https://user-images.githubusercontent.com/14296959/84499063-fff0ae00-acdb-11ea-80c6-b93142c5b8a1.png)

But it was error 
![image](https://user-images.githubusercontent.com/14296959/84499095-126ae780-acdc-11ea-8fb2-ad6135b713fb.png)

**Comment by LarsBaertschi** [comment] 2020-06-13 23:41
Hey, I'm unable to reproduce the issue you mentioned.

In what directory do you execute the `serve` command? It should be in the root directory.

Else for further analysis, what do you get if you open up `http://localhost:5000`?

**Comment by socktow** [comment] 2020-06-15 08:30
> Hey, I'm unable to reproduce the issue you mentioned.
> 
> In what directory do you execute the `serve` command? It should be in the root directory.
> 
> Else for further analysis, what do you get if you open up `http://localhost:5000`?

![image](https://user-images.githubusercontent.com/14296959/84635231-1fc2e480-af1d-11ea-8b69-3a591a1e2253.png)
i have this , that it mean i must do something to run layout ?

**Comment by LarsBaertschi** [comment] 2020-06-15 09:03
By the `root` directory, I mean really the highest directory inside the project. Currently it looks like you're running the `serve` command in the "/backend-build" folder.

Basically, you need to statically serve the HTML files in layouts/layout-simple. Please note that the simple layout is not ready-for-use, but meant to be adapted using simple html, css and some js.

**Comment by LarsBaertschi** [comment] 2020-07-14 05:43
Closing because it's stalled. Please contact us again if your issue persists.

**Closed by LarsBaertschi** 2020-07-14 05:43 UTC
